-- Cohort 1: New users of celecoxib
-- Generated by R/cohorts.R from config/cohorts.yml on 2026-08-19
-- OHDSI SQL, before dialect translation.

WITH entry_events AS (
  SELECT e.person_id,
          e.drug_exposure_start_date AS event_date,
          e.drug_exposure_end_date AS event_end_date
   FROM main.drug_exposure e
   WHERE e.drug_concept_id IN (1118084)
),
index_event AS (
  SELECT person_id, MIN(event_date) AS cohort_start_date
   FROM entry_events
   GROUP BY person_id
),
inc_01_prior_observation AS (
  SELECT p.person_id, p.cohort_start_date
   FROM index_event p
   INNER JOIN main.observation_period op
     ON op.person_id = p.person_id
    AND p.cohort_start_date >= op.observation_period_start_date
    AND p.cohort_start_date <= op.observation_period_end_date
   WHERE DATEDIFF(DAY, op.observation_period_start_date, p.cohort_start_date) >= 365
     AND DATEDIFF(DAY, p.cohort_start_date, op.observation_period_end_date) >= 0
),
inc_02_observation_after_index AS (
  SELECT p.person_id, p.cohort_start_date
   FROM inc_01_prior_observation p
   INNER JOIN main.observation_period op
     ON op.person_id = p.person_id
    AND p.cohort_start_date >= op.observation_period_start_date
    AND p.cohort_start_date <= op.observation_period_end_date
   WHERE DATEDIFF(DAY, op.observation_period_start_date, p.cohort_start_date) >= 0
     AND DATEDIFF(DAY, p.cohort_start_date, op.observation_period_end_date) >= 1
),
inc_03_age_at_index AS (
  SELECT p.person_id, p.cohort_start_date
   FROM inc_02_observation_after_index p
   INNER JOIN main.person pe ON pe.person_id = p.person_id
   WHERE (YEAR(p.cohort_start_date) - pe.year_of_birth) >= 18
),
exc_01_no_prior_outcome AS (
  SELECT p.person_id, p.cohort_start_date
   FROM inc_03_age_at_index p
   WHERE NOT EXISTS (
     SELECT 1 FROM main.condition_occurrence x
      WHERE x.person_id = p.person_id
        AND x.condition_concept_id IN (192671)
        AND x.condition_start_date < p.cohort_start_date
   )
),
exc_02_no_comparator_exposure AS (
  SELECT p.person_id, p.cohort_start_date
   FROM exc_01_no_prior_outcome p
   WHERE NOT EXISTS (
     SELECT 1 FROM main.drug_exposure x
      WHERE x.person_id = p.person_id
        AND x.drug_concept_id IN (1124300)
        AND x.drug_exposure_start_date <= p.cohort_start_date
   )
),
cohort_final AS (
  SELECT p.person_id, p.cohort_start_date, e.era_end_date AS cohort_end_date
   FROM exc_02_no_comparator_exposure p
   INNER JOIN (
     SELECT person_id, MIN(exp_start) AS era_start_date, MAX(exp_end) AS era_end_date
     FROM (
       SELECT person_id, exp_start, exp_end,
              SUM(is_new_era) OVER (PARTITION BY person_id ORDER BY exp_start
                                    ROWS UNBOUNDED PRECEDING) AS era_number
       FROM (
         SELECT person_id, exp_start, exp_end,
                CASE WHEN prior_max_end IS NULL
                       OR exp_start > DATEADD(DAY, 30, prior_max_end)
                     THEN 1 ELSE 0 END AS is_new_era
         FROM (
           SELECT person_id,
                  drug_exposure_start_date AS exp_start,
                  drug_exposure_end_date AS exp_end,
                  MAX(drug_exposure_end_date) OVER (PARTITION BY person_id ORDER BY drug_exposure_start_date
                                ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING)
                    AS prior_max_end
           FROM main.drug_exposure
           WHERE drug_concept_id IN (1118084)
         ) t1
       ) t2
     ) t3
     GROUP BY person_id, era_number
   ) e
     ON e.person_id = p.person_id
    AND e.era_start_date = p.cohort_start_date
)
SELECT CAST(1 AS INT) AS cohort_definition_id,
       person_id AS subject_id,
       cohort_start_date,
       cohort_end_date
FROM cohort_final
