-- Cohort 3: Gastrointestinal bleeding (outcome cohort)
-- Generated by R/cohorts.R from config/cohorts.yml on 2026-08-19
-- OHDSI SQL, before dialect translation.

WITH entry_events AS (
  SELECT e.person_id,
          e.condition_start_date AS event_date,
          e.condition_end_date AS event_end_date
   FROM main.condition_occurrence e
   WHERE e.condition_concept_id IN (192671)
),
index_event AS (
  SELECT person_id, MIN(event_date) AS cohort_start_date
   FROM entry_events
   GROUP BY person_id
),
cohort_final AS (
  SELECT person_id, cohort_start_date, cohort_start_date AS cohort_end_date
   FROM index_event
)
SELECT CAST(3 AS INT) AS cohort_definition_id,
       person_id AS subject_id,
       cohort_start_date,
       cohort_end_date
FROM cohort_final
